// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extension.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v2 "github.com/sensu/sensu-go/api/core/v2"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HandleEventRequest struct {
	Event                *v2.Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	MutatedEvent         []byte    `protobuf:"bytes,2,opt,name=mutated_event,json=mutatedEvent,proto3" json:"mutated_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HandleEventRequest) Reset()         { *m = HandleEventRequest{} }
func (m *HandleEventRequest) String() string { return proto.CompactTextString(m) }
func (*HandleEventRequest) ProtoMessage()    {}
func (*HandleEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_extension_31137cd3cf7221a0, []int{0}
}
func (m *HandleEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleEventRequest.Unmarshal(m, b)
}
func (m *HandleEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleEventRequest.Marshal(b, m, deterministic)
}
func (dst *HandleEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleEventRequest.Merge(dst, src)
}
func (m *HandleEventRequest) XXX_Size() int {
	return xxx_messageInfo_HandleEventRequest.Size(m)
}
func (m *HandleEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleEventRequest proto.InternalMessageInfo

func (m *HandleEventRequest) GetEvent() *v2.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *HandleEventRequest) GetMutatedEvent() []byte {
	if m != nil {
		return m.MutatedEvent
	}
	return nil
}

type HandleEventResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleEventResponse) Reset()         { *m = HandleEventResponse{} }
func (m *HandleEventResponse) String() string { return proto.CompactTextString(m) }
func (*HandleEventResponse) ProtoMessage()    {}
func (*HandleEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_extension_31137cd3cf7221a0, []int{1}
}
func (m *HandleEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleEventResponse.Unmarshal(m, b)
}
func (m *HandleEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleEventResponse.Marshal(b, m, deterministic)
}
func (dst *HandleEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleEventResponse.Merge(dst, src)
}
func (m *HandleEventResponse) XXX_Size() int {
	return xxx_messageInfo_HandleEventResponse.Size(m)
}
func (m *HandleEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleEventResponse proto.InternalMessageInfo

func (m *HandleEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *HandleEventResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type MutateEventRequest struct {
	Event                *v2.Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MutateEventRequest) Reset()         { *m = MutateEventRequest{} }
func (m *MutateEventRequest) String() string { return proto.CompactTextString(m) }
func (*MutateEventRequest) ProtoMessage()    {}
func (*MutateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_extension_31137cd3cf7221a0, []int{2}
}
func (m *MutateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateEventRequest.Unmarshal(m, b)
}
func (m *MutateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateEventRequest.Marshal(b, m, deterministic)
}
func (dst *MutateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateEventRequest.Merge(dst, src)
}
func (m *MutateEventRequest) XXX_Size() int {
	return xxx_messageInfo_MutateEventRequest.Size(m)
}
func (m *MutateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutateEventRequest proto.InternalMessageInfo

func (m *MutateEventRequest) GetEvent() *v2.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type MutateEventResponse struct {
	MutatedEvent         []byte   `protobuf:"bytes,1,opt,name=mutated_event,json=mutatedEvent,proto3" json:"mutated_event,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateEventResponse) Reset()         { *m = MutateEventResponse{} }
func (m *MutateEventResponse) String() string { return proto.CompactTextString(m) }
func (*MutateEventResponse) ProtoMessage()    {}
func (*MutateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_extension_31137cd3cf7221a0, []int{3}
}
func (m *MutateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateEventResponse.Unmarshal(m, b)
}
func (m *MutateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateEventResponse.Marshal(b, m, deterministic)
}
func (dst *MutateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateEventResponse.Merge(dst, src)
}
func (m *MutateEventResponse) XXX_Size() int {
	return xxx_messageInfo_MutateEventResponse.Size(m)
}
func (m *MutateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutateEventResponse proto.InternalMessageInfo

func (m *MutateEventResponse) GetMutatedEvent() []byte {
	if m != nil {
		return m.MutatedEvent
	}
	return nil
}

func (m *MutateEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FilterEventRequest struct {
	Event                *v2.Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FilterEventRequest) Reset()         { *m = FilterEventRequest{} }
func (m *FilterEventRequest) String() string { return proto.CompactTextString(m) }
func (*FilterEventRequest) ProtoMessage()    {}
func (*FilterEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_extension_31137cd3cf7221a0, []int{4}
}
func (m *FilterEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterEventRequest.Unmarshal(m, b)
}
func (m *FilterEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterEventRequest.Marshal(b, m, deterministic)
}
func (dst *FilterEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterEventRequest.Merge(dst, src)
}
func (m *FilterEventRequest) XXX_Size() int {
	return xxx_messageInfo_FilterEventRequest.Size(m)
}
func (m *FilterEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterEventRequest proto.InternalMessageInfo

func (m *FilterEventRequest) GetEvent() *v2.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type FilterEventResponse struct {
	Filtered             bool     `protobuf:"varint,1,opt,name=filtered" json:"filtered,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterEventResponse) Reset()         { *m = FilterEventResponse{} }
func (m *FilterEventResponse) String() string { return proto.CompactTextString(m) }
func (*FilterEventResponse) ProtoMessage()    {}
func (*FilterEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_extension_31137cd3cf7221a0, []int{5}
}
func (m *FilterEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterEventResponse.Unmarshal(m, b)
}
func (m *FilterEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterEventResponse.Marshal(b, m, deterministic)
}
func (dst *FilterEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterEventResponse.Merge(dst, src)
}
func (m *FilterEventResponse) XXX_Size() int {
	return xxx_messageInfo_FilterEventResponse.Size(m)
}
func (m *FilterEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterEventResponse proto.InternalMessageInfo

func (m *FilterEventResponse) GetFiltered() bool {
	if m != nil {
		return m.Filtered
	}
	return false
}

func (m *FilterEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*HandleEventRequest)(nil), "sensu.rpc.HandleEventRequest")
	proto.RegisterType((*HandleEventResponse)(nil), "sensu.rpc.HandleEventResponse")
	proto.RegisterType((*MutateEventRequest)(nil), "sensu.rpc.MutateEventRequest")
	proto.RegisterType((*MutateEventResponse)(nil), "sensu.rpc.MutateEventResponse")
	proto.RegisterType((*FilterEventRequest)(nil), "sensu.rpc.FilterEventRequest")
	proto.RegisterType((*FilterEventResponse)(nil), "sensu.rpc.FilterEventResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Extension service

type ExtensionClient interface {
	HandleEvent(ctx context.Context, in *HandleEventRequest, opts ...grpc.CallOption) (*HandleEventResponse, error)
	MutateEvent(ctx context.Context, in *MutateEventRequest, opts ...grpc.CallOption) (*MutateEventResponse, error)
	FilterEvent(ctx context.Context, in *FilterEventRequest, opts ...grpc.CallOption) (*FilterEventResponse, error)
}

type extensionClient struct {
	cc *grpc.ClientConn
}

func NewExtensionClient(cc *grpc.ClientConn) ExtensionClient {
	return &extensionClient{cc}
}

func (c *extensionClient) HandleEvent(ctx context.Context, in *HandleEventRequest, opts ...grpc.CallOption) (*HandleEventResponse, error) {
	out := new(HandleEventResponse)
	err := grpc.Invoke(ctx, "/sensu.rpc.Extension/HandleEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) MutateEvent(ctx context.Context, in *MutateEventRequest, opts ...grpc.CallOption) (*MutateEventResponse, error) {
	out := new(MutateEventResponse)
	err := grpc.Invoke(ctx, "/sensu.rpc.Extension/MutateEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionClient) FilterEvent(ctx context.Context, in *FilterEventRequest, opts ...grpc.CallOption) (*FilterEventResponse, error) {
	out := new(FilterEventResponse)
	err := grpc.Invoke(ctx, "/sensu.rpc.Extension/FilterEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Extension service

type ExtensionServer interface {
	HandleEvent(context.Context, *HandleEventRequest) (*HandleEventResponse, error)
	MutateEvent(context.Context, *MutateEventRequest) (*MutateEventResponse, error)
	FilterEvent(context.Context, *FilterEventRequest) (*FilterEventResponse, error)
}

func RegisterExtensionServer(s *grpc.Server, srv ExtensionServer) {
	s.RegisterService(&_Extension_serviceDesc, srv)
}

func _Extension_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensu.rpc.Extension/HandleEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).HandleEvent(ctx, req.(*HandleEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_MutateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).MutateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensu.rpc.Extension/MutateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).MutateEvent(ctx, req.(*MutateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extension_FilterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServer).FilterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensu.rpc.Extension/FilterEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServer).FilterEvent(ctx, req.(*FilterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Extension_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sensu.rpc.Extension",
	HandlerType: (*ExtensionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleEvent",
			Handler:    _Extension_HandleEvent_Handler,
		},
		{
			MethodName: "MutateEvent",
			Handler:    _Extension_MutateEvent_Handler,
		},
		{
			MethodName: "FilterEvent",
			Handler:    _Extension_FilterEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extension.proto",
}

func init() { proto.RegisterFile("extension.proto", fileDescriptor_extension_31137cd3cf7221a0) }

var fileDescriptor_extension_31137cd3cf7221a0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xbe, 0xb4, 0x34, 0xd3, 0xbe, 0x08, 0x5b, 0x91, 0x52, 0x50, 0x4a, 0xbc, 0xf4,
	0xe2, 0x06, 0xe3, 0x37, 0x50, 0xab, 0x5e, 0x14, 0xc9, 0xd1, 0x8b, 0xa4, 0xe9, 0x58, 0x03, 0xed,
	0xee, 0xba, 0x7f, 0x8a, 0xdf, 0xdd, 0x8b, 0x64, 0x37, 0xd6, 0x2c, 0x89, 0xa7, 0x5e, 0x02, 0x33,
	0x99, 0xfd, 0xcd, 0x33, 0xcf, 0x0c, 0x1c, 0xe1, 0xa7, 0x46, 0xa6, 0x0a, 0xce, 0xa8, 0x90, 0x5c,
	0x73, 0x12, 0x2a, 0x64, 0xca, 0x50, 0x29, 0xf2, 0xe9, 0xe5, 0xba, 0xd0, 0xef, 0x66, 0x49, 0x73,
	0xbe, 0x8d, 0x6d, 0xd6, 0x7d, 0x2f, 0xd6, 0x3c, 0xce, 0x44, 0x11, 0xe7, 0x5c, 0x62, 0xbc, 0x4b,
	0x62, 0xdc, 0x21, 0xd3, 0xee, 0x75, 0x54, 0x00, 0x79, 0xc8, 0xd8, 0x6a, 0x83, 0x8b, 0x32, 0x99,
	0xe2, 0x87, 0x41, 0xa5, 0x09, 0x85, 0x9e, 0x2d, 0x9a, 0x04, 0xb3, 0x60, 0x3e, 0x4c, 0x26, 0xd4,
	0xf5, 0xc8, 0x44, 0x41, 0x4b, 0x08, 0xdd, 0x25, 0xd4, 0xd5, 0xbb, 0x32, 0x72, 0x0e, 0xff, 0xb7,
	0x46, 0x67, 0x1a, 0x57, 0xaf, 0xee, 0x5d, 0x77, 0x16, 0xcc, 0x47, 0xe9, 0xa8, 0x4a, 0xda, 0xda,
	0xe8, 0x06, 0xc6, 0x5e, 0x2b, 0x25, 0x38, 0x53, 0x48, 0x8e, 0xa1, 0x87, 0x52, 0x72, 0x69, 0x7b,
	0x85, 0xa9, 0x0b, 0xc8, 0x09, 0xf4, 0xb9, 0xd1, 0xc2, 0x38, 0x54, 0x98, 0x56, 0x51, 0x74, 0x0b,
	0xe4, 0xd1, 0x42, 0x0f, 0xd1, 0x1b, 0x3d, 0xc3, 0xd8, 0xa3, 0x54, 0x52, 0x1a, 0x63, 0x04, 0xcd,
	0x31, 0x7e, 0xf5, 0x76, 0x6b, 0x7a, 0x4b, 0x5d, 0x77, 0xc5, 0x46, 0xa3, 0x3c, 0x48, 0xd7, 0x3d,
	0x8c, 0x3d, 0x4a, 0xa5, 0x6b, 0x0a, 0x83, 0x37, 0x9b, 0xc6, 0x95, 0x25, 0x0d, 0xd2, 0x7d, 0xdc,
	0x2e, 0x27, 0xf9, 0x0a, 0x20, 0x5c, 0xfc, 0x1c, 0x0a, 0x79, 0x82, 0x61, 0xcd, 0x79, 0x72, 0x4a,
	0xf7, 0x27, 0x43, 0x9b, 0xcb, 0x9f, 0x9e, 0xfd, 0xf5, 0xdb, 0xa9, 0x89, 0x3a, 0x25, 0xaf, 0x66,
	0x9f, 0xc7, 0x6b, 0x2e, 0xc7, 0xe3, 0xb5, 0xb8, 0xee, 0x78, 0xb5, 0xb1, 0x3d, 0x5e, 0xd3, 0x54,
	0x8f, 0xd7, 0xe2, 0x56, 0xd4, 0xb9, 0xee, 0xbd, 0xfc, 0x93, 0x22, 0x5f, 0xf6, 0xed, 0x89, 0x5f,
	0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x58, 0x0c, 0x6c, 0x33, 0x03, 0x00, 0x00,
}
